name: build workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v5.0.0
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: cd ./api && node app.js
  
